sudo: false

language: php

branches:
    only:
        - master

notifications:
    email: false

.template_phpunit: &phpunit
    stage: test
    services:
        - docker
    before_install:
        - stty cols 120
        - phpenv config-rm xdebug.ini || echo "xdebug not available"
        - ./tests/setup.sh
    install: composer install --no-interaction --no-progress --ansi
    script: ./tests/run.sh
    env:
        SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT: 1
    cache:
        directories:
            - $HOME/.composer/cache/files

.template_phpunit_low: &phpunit_low
    <<: *phpunit
    install:
        - composer require --dev "sebastian/comparator:^2.0"
        - composer update --no-interaction --no-progress --ansi --prefer-lowest --prefer-stable
    env:
        COMMENT: "low deps"
        SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT: 1

.template_phpunit_high: &phpunit_high
    <<: *phpunit
    install: composer update --no-interaction --no-progress --ansi
    env:
        COMMENT: "high deps"
        SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT: 1

jobs:
    include:
        -   stage: coding-style
            php: 7.2
            install:
                - wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.16.1/php-cs-fixer.phar -q
            script:
                - php php-cs-fixer.phar fix --dry-run --diff

        -   <<: *phpunit
            dist: trusty
            php: 5.5
        -   <<: *phpunit
            php: 5.6
        -   <<: *phpunit_low
            php: 7.0
        -   <<: *phpunit
            php: 7.1
        -   <<: *phpunit
            php: 7.2
        -   <<: *phpunit
            php: 7.3
        -   <<: *phpunit_high
            php: 7.4

        -   stage: split
            php: 7.4
            cache:
                directories:
                    - $HOME/.gitsplit/cache
            if: branch = master AND fork = false
            install:
                - docker pull jderusse/gitsplit:2.0
                - git config remote.origin.fetch "+refs/*:refs/*"
                - git config remote.origin.mirror true
                - git fetch --unshallow || true
            env:
                COMMENT: "split repo"
            script:
                - docker run --rm -t -e GH_TOKEN -v "$HOME/.gitsplit/cache":/cache/gitsplit -v ${PWD}:/srv jderusse/gitsplit:2.0 gitsplit --ref "${TRAVIS_BRANCH}";
